# 開発環境用のオーバーライド設定

services:
  backend:
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
    command: npm run dev

  frontend:
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    stdin_open: true
    tty: true

volumes:
  backend_node_modules:
  frontend_node_modules:
  frontend_next: